require File.expand_path("../config/boot", __FILE__)
require "rake/testtask"
require "rails"
require "rails/tasks"

task :default => :test

Rake::TestTask.new do |t|
  t.test_files = FileList['test/**/*_test.rb']
  t.libs << "test"
  t.verbose = true
end

task :environment do
  Rails.application.initialize!
end

