require "rake/testtask"

task :default => :test

Rake::TestTask.new do |t|
  t.test_files = FileList['test/**/*_test.rb']
  t.libs << "test"
  t.verbose = true
end

task :environment do
  require File.expand_path("../config/boot", __FILE__)
  require "rails/tasks"
  Rails.application.initialize!
end

